### ISSUE TITLE
1.1.1. Admin API for updating item-id and unique attribute of a resource 

### ISSUE THREAD

**Issue by swaminathanvasanth** [datakaveri/iudx-resource-server#143]
For details about the API refer to the SRS document (section 1.1.1)

For Create, Update and Delete, the API should perform the following: 

- Create, Update or Delete the information in PostgresQL
- Broadcast this information over internal RabbitMQ

Information on the exchange to publish is as described in the SRS document (section 1.5)

**Comment by kailash** [comment]
resolved through PR #170
