### ISSUE TITLE
1.12. Store subscription information

### ISSUE THREAD

**Issue by swaminathanvasanth** [datakaveri/iudx-resource-server#150]
We need to incorporate a routine where the subscription information is stored in the database. It should contain the following information

- id (queue-name)
- entities (routing-key)
- last-refreshed-time

**Comment by kailash** [comment]
Subscriptions are stored in DB according to the schema defined: [here](https://github.com/datakaveri/iudx-resource-server/blob/master/src/main/resources/db/migration/V1__init-tables.sql)
