### ISSUE TITLE
Elastic client  issue

### ISSUE THREAD

**Issue by abhi4578** [datakaveri/iudx-resource-server#200]
**Issue**

The rs query requests are working alternatively i.e. elastic client  and in turn rs is able to return data for only alternate queries. Was it not working for a specific request or for all requests which involved elastic client. @swaminathanvasanth ? 

Find the error Logs (important  ones, attached detailed log  [elastic-client-exception.txt](https://github.com/datakaveri/iudx-resource-server/files/8138606/elastic-client-exception.txt)) 

```
    time=2022-02-15T08:54:08+0000 level="INFO" loggerName=iudx.resource.server.database.archives.
QueryDecoder message="Info: Temporal Search block" source=rs sourceUrl=https://rs.iudx.org.in exception=""
    time=2022-02-15T08:54:08+0000 level="[1;31mERROR[m" loggerName=io.vertx.core.impl.ContextImpl message="Unhandled exception" source=rs sourceUrl=https://rs.iudx.org.in exception=" java.lang.StringIndexOutOfBoundsException: begin -1, end 0, length 55|	at java.lang.String.checkBoundsBeginEnd(Unknown Source) ~[?:?]|	at java.lang.String.substring(Unknown Source) ~[?:?]|	at iudx.resource.server.database.archives.ElasticClient$2.onFailure(ElasticClient.java:161) ~[fatjar.jar:?]|	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:317) ~[fatjar.jar:?]|	at iudx.resource.server.database.archives.ElasticClient.countAsync(ElasticClient.java:124) ~[fatjar.jar:?]|	at iudx.resource.server.database.archives.DatabaseServiceImpl.searchQuery(DatabaseServiceImpl.java:124) ~[fatjar.jar:?]|	at iudx.resource.server.database.archives.DatabaseServiceVertxProxyHandler.handle(DatabaseServiceVertxProxyHandler.java:124) ~[fatjar.jar:?]|	at iudx.resource.server.database.archives.DatabaseServiceVertxProxyHandler.handle(DatabaseServiceVertxProxyHandler.java:52) ~[fatjar.jar:?]|	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:52) ~[fatjar.jar:?]|	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:194) ~[fatjar.jar:?]|	at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177) ~[fatjar.jar:?]|	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:163) ~[fatjar.jar:?]|	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:128) ~[fatjar.jar:?]|	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:107) ~[fatjar.jar:?]|	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:104) ~[fatjar.jar:?]|	at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183) ~[fatjar.jar:?]|	at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168) ~[fatjar.jar:?]|	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54) ~[fatjar.jar:?]|	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[fatjar.jar:?]|	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[fatjar.jar:?]|	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[fatjar.jar:?]|	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[fatjar.jar:?]|	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[fatjar.jar:?]|	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[fatjar.jar:?]|	at java.lang.Thread.run(Unknown Source) [?:?]|"
    time=2022-02-15T08:54:08+0000 level="[1;31mERROR[m" loggerName=iudx.resource.server.database.archives.ElasticClient message="Request cannot be executed; I/O reactor status: STOPPED" source=rs sourceUrl=https://rs.iudx.org.in exception=""

``` 

**Troubleshooting**
1. Restarting the pod made it work. That is alternate search query did not fail and there was no exception.

**Possible Issue/Solution**

1. The application code corresponding to this error is happening in ElasticClient.java file during  ```performRequestAsync  on Failure method``` . There is an unhandled exception happening during some string related operation. This is probably in turn  causing a known [elastic client issue - Request cannot be executed; I/O reactor status stopped](https://discuss.elastic.co/t/request-cannot-be-executed-i-o-reactor-status-stopped/195438/6) . This elastic client issue causes the connection to be closed and subsequent requests will fail with the error reported as in the second log and there by the request will fail and no data is returned. 
 In current-deployment branch, at the code 
https://github.com/datakaveri/iudx-resource-server/blob/03915b13a5b71a27183d5d3280a45c65690462b0/src/main/java/iudx/resource/server/database/archives/ElasticClient.java#L161
  
  and at current master branch at https://github.com/datakaveri/iudx-resource-server/blob/b239da21384373215a56fd0d29487105491dccc1/src/main/java/iudx/resource/server/database/archives/elastic/ElasticClient.java#L172
  
  3.The workaround suggested is to ensure that no exceptions are thrown out of your onFailure methods.
 4. What caused the the request to go to  ```performRequestAsync  on Failure method``` ? Most probably, some connection issue with elasticsearch  initially that caused  failure which in turn  likely triggered known elastic issue through string exception in ```onFailure``` method and  then causing cyclical problem. 

PS: The logs are obtained from loki through grafana, there might some reordering (as many have same timestamp).

**Comment by swaminathanvasanth** [comment]
It was for all the requests made to the Elastic client @abhi4578

**Comment by abhi4578** [comment]
I can trace back the origins of failure of requests from 08 Feb . Initially it was a connection timeout issue - , that would have triggered. Attached detailed log of origins [elastic-execptions-origins.txt](https://github.com/datakaveri/iudx-resource-server/files/8138793/elastic-execptions-origins.txt). 
```
time=2022-02-08T09:55:41+0000 level="[1;31mERROR[m" loggerName=iudx.resource.server.database.archives.ElasticClient message="Timeout connecting to [elasticsearch-mcd-headless.elastic.svc.cluster.local/10.42.153.136:9200]" source=rs sourceUrl=https://rs.iudx.org.in exception=""
022-02-08 15:25:41	
ERROR [InternalHttpAsyncClient:66] 2022-02-08 09:55:41,032 - I/O reactor terminated abnormally
	
2022-02-08 15:25:41	
java.lang.StringIndexOutOfBoundsException: begin -1, end 0, length 26
	
2022-02-08 15:25:41	
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	
2022-02-08 15:25:41	
	at java.base/java.lang.String.substring(Unknown Source)
	
2022-02-08 15:25:41	
	at iudx.resource.server.database.archives.ElasticClient$2.onFailure(ElasticClient.java:161)
	
2022-02-08 15:25:41	
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:598)
	
2022-02-08 15:25:41	
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:359)
	
2022-02-08 15:25:41	
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:348)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:392)
	
2022-02-08 15:25:41	
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.failed(PoolingNHttpClientConnectionManager.java:316)
	
2022-02-08 15:25:41	
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
	
2022-02-08 15:25:41	
	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:169)
	
2022-02-08 15:25:41	
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:628)
	
2022-02-08 15:25:41	
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:894)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:184)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:214)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:158)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
	
2022-02-08 15:25:41	
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	
2022-02-08 15:25:41	
	at java.base/java.lang.Thread.run(Unknown Source)
	
2022-02-08 15:25:41	
time=2022-02-08T09:55:41+0000 level="[1;31mERROR[m" loggerName=iudx.resource.server.database.archives.ElasticClient message="Timeout connecting to [elasticsearch-mcd-headless.elastic.svc.cluster.local/10.42.153.136:9200]" source=rs sourceUrl=https://rs.iudx.org.in exception=""

```

- The above timeout issue  -> made the request fail and goto ```OnFailure method ```  -> which in turn triggered string exception -> which triggered reactor stop --> resulting in failure in subsequent requests --> ```OnFailure method``` --> ...

**Comment by abhi4578** [comment]
The reason like for alternate query suceeding is, in a pod two verticles are deployed. So this issue triigger would have happened in one of verticle but not the other.

**Comment by abhi4578** [comment]
Handling the string out of bounds exception should solve the problem.  at  In current-deployment branch, at the code 
https://github.com/datakaveri/iudx-resource-server/blob/03915b13a5b71a27183d5d3280a45c65690462b0/src/main/java/iudx/resource/server/database/archives/ElasticClient.java#L161
  
  and at current master branch at https://github.com/datakaveri/iudx-resource-server/blob/b239da21384373215a56fd0d29487105491dccc1/src/main/java/iudx/resource/server/database/archives/elastic/ElasticClient.java#L172

**Comment by abhi4578** [comment]
but can any other exceptions happen in that method? if so can have a generalized exception catacher inside failure method, so that no exception leave onFailure method .

**Comment by abhi4578** [comment]
This also should be fixed in other parts of elastic client.
https://github.com/datakaveri/iudx-resource-server/blob/03915b13a5b71a27183d5d3280a45c65690462b0/src/main/java/iudx/resource/server/database/archives/ElasticClient.java#L92

https://github.com/datakaveri/iudx-resource-server/blob/b239da21384373215a56fd0d29487105491dccc1/src/main/java/iudx/resource/server/database/archives/elastic/ElasticClient.java#L103


 This issue might happen in other IUDX servers which uses elastic client - file-server, catalogue. It needs to be checked the against (the possible methods)[https://discuss.elastic.co/t/request-cannot-be-executed-i-o-reactor-status-stopped/195438/6] and fixed appropriately.

**Comment by kailash** [comment]
fixed and resolved
