### ISSUE TITLE
Need More Information to Configure Resource Server

### ISSUE THREAD

**Issue by pachori91** [datakaveri/iudx-resource-server#301]
Hi Team,

I am trying to start Resource Server v3.5.0 on my local and trying to config it by following https://github.com/datakaveri/iudx-resource-server/blob/v3.5.0/SETUP.md 

I provided all information for verticle iudx.resource.server.databroker.DataBrokerVerticle as mentioned in above link.

But when i am trying to run my instance using command "mvn clean compile exec:java@resource-server" then i am getting error as below logs-

level="ERROR" loggerName=iudx.resource.server.databroker.listeners.RevokeClientQListener message="Rabbit client startup failed.java.lang.IllegalStateException: Invalid configuration: **'virtualHost'** must be non-null." source=rs sourceUrl=http://localhost exception=""

Looks like we need to add virtualHost property for this virticle. I am not sure what should be value for virtualHost can you please guide me for same.

And can you guys please provide me a complete sample config file with description about the values to be provide. 

Thanks
Deepak Kumar

**Comment by kailash** [comment]
Hi @pachori91 

Please use the below configs for Databroker Verticle.

```json
{
	"id": "iudx.resource.server.databroker.DataBrokerVerticle",
	"isWorkerVerticle": false,
	"verticleInstances": 1,
	"dataBrokerIP": "",
	"dataBrokerPort": 29042,
	
	"prodVhost": "IUDX",
	"internalVhost": "IUDX-INTERNAL",
	"externalVhost": "IUDX-EXTERNAL",
	
	"dataBrokerUserName": "",
	"dataBrokerPassword": "",
	"dataBrokerManagementPort": 1234,
	"connectionTimeout": 6000,
	"requestedHeartbeat": 60,
	"handshakeTimeout": 6000,
	"requestedChannelMax": 5,
	"networkRecoveryInterval": 500,
	"automaticRecoveryEnabled": "true",
	"postgresDatabaseIP": "",
	"postgresDatabasePort": 1234,
	"postgresDatabaseName": "",
	"postgresDatabaseUserName": "",
	"postgresDatabasePassword": "",
	"postgrespoolSize": 25,
	"brokerAmqpIp": "",
	"brokerAmqpPort": 24567
}


```

**Comment by kailash** [comment]
@pachori91 Is this solved your vHost issue?

**Comment by pachori91** [comment]
hi @kailash,

Thanks for your reply.

As i have followed [Databroker setup](https://github.com/datakaveri/iudx-deployment/tree/3.5.0/Docker-Swarm-deployment/single-node/databroker) to install rabbitmq and it is not creating any virtual host on Rabbit mq.

So do i need to create these virtual hosts manually?

Can you please tell me the configuration or setup i need to perform on RabbitMq before using it for Resource Server.

Thanks
Deepak Kumar

**Comment by kailash** [comment]
@pachori91 

Yes, you have to create them manually. for detailed instructions please follow this comment by Abhilash on #302, [comment](https://github.com/datakaveri/iudx-resource-server/issues/302#issuecomment-1240616817)
