### ISSUE TITLE
Is there any missing configuration need to be perform to setup resource server?

### ISSUE THREAD

**Issue by pachori91** [datakaveri/iudx-resource-server#302]
Hi Team,

I have setup Resource Server(3.5.0) on my local by following steps and configuration mentioned [here](https://github.com/datakaveri/iudx-resource-server/blob/v3.5.0/README.md).

And to install dependency stack i used [Deployment Repo](https://github.com/datakaveri/iudx-deployment/tree/3.5.0/Docker-Swarm-deployment/single-node).

So finally my resource server instace is up and able to access api but not checked with real example just able to access APIs for now.

My question is, Do we need to follow configration steps other then mentioned in above links or these are sufficent?

I am asking this question as i did same for auth and catalogue server but after discussion with iudx team, found there are some other missing configurations need to be perform before using respective APIs even i followed installation quide properly.

Thanks
Deepak Kumar

**Comment by abhi4578** [comment]
Hi deepak (@pachori91 )

One more step I feel that left out is Rabbitmq configuration, It needs to be configured with appropriate vhosts, exchanges,queues and bindings. Please find the docs below:

- Login to UI at `` https://<RMQ-domain-name>:28041/ `` as admin user.

- Configure appropriate vhosts, exchanges, queues and bindings  from UI  as given in the below table: 
  
  1. **Create vHosts**: Goto Admin-> Virtual Hosts -> add virtual host at the bottom by entering the name. Following vhosts needs to be added
  
  |vHost| | | |
  |:---:|:---:|:---:|:---:|
  |IUDX| | | |
  |IUDX-EXTERNAL| | | |
  |IUDX-INTERNAL| | | |
  
  2. **Create queues**: Goto Queues -> Add queue by entering the name, select appropriate vhost , rest all defaults. Following queues needs to be created
  
  |VHOST|Queues Name|
  |:---:|:---:|
  |IUDX-INTERNAL|fs-invalid-sub|
  |IUDX-INTERNAL|gis-invalid-sub|
  |IUDX-INTERNAL|lip-invalid-sub|
  |IUDX-INTERNAL|lip-processed-messages|
  |IUDX-INTERNAL|lip-unique-attributes|
  |IUDX-INTERNAL|rs-invalid-sub|
  |IUDX-INTERNAL|rs-unique-attributes|
  |IUDX|database|
  |IUDX|redis-latest|
  
  3. **Create Exchanges**: Goto Exchanges -> Add a new Exchange by entering the name, select appropriate vHost, type , rest all defaults
  
  |VHOST|Exchange Name|Type of exchange|
  |:---:|:---:|:---:|
  |IUDX-INTERNAL|invalid-sub|topic|
  |IUDX-INTERNAL|latest-data-unique-attributes|topic|
  |IUDX-INTERNAL|processed-messages|topic|
  
  4. **Create Exchange-Queue bindings**: Goto particular vHost -> particular exchange ->Bindings-> enter queue name to bind to, add routing key-> bind
  
  | VHOST         | Exchange                      | Queue                  | Routing<br>key |
  | ------------- | ----------------------------- | ---------------------- | -------------- |
  | IUDX-INTERNAL | invalid-sub                   | fs-invalid-sub         | #              |
  | IUDX-INTERNAL | invalid-sub                   | gis-invalid-sub        | #              |
  | IUDX-INTERNAL | invalid-sub                   | lip-invalid-sub        | #              |
  | IUDX-INTERNAL | invalid-sub                   | rs-invalid-sub         | #              |
  | IUDX-INTERNAL | latest-data-unique-attributes | lip-unique-attributes  | #              |
  | IUDX-INTERNAL | latest-data-unique-attributes | rs-unique-attributes   | #              |
  | IUDX-INTERNAL | processed-messages            | lip-processed-messages | #              |
  



Regards
Abhilash

**Comment by pachori91** [comment]
Hi Team,

I have followed [Register Adaptor for Resouce](https://docs.iudx.org.in/docs/provider/provider_register_resource_server/) on my Local Instance to register adaptor.

Finally i got databroker enpoint with credential.

Below are my Further queries 
-  do i need to write to same exchange which provided as "id" in Register Adpator API's response or no need to mention exchange while pushing data to RabbitMq?
- Is the route_key will be same as exchange id?
- Does same thing apply for public IUDX Server?


@kailash i am asking this question again as same is not answered yet.

Thanks
Deepak Kumar

**Comment by kailash** [comment]
Hi @pachori91 

1. Yes, you need to use id in response as an exchange to push messages.
2. Route Key should be derived from id. 
for an id like `111/222/333/444/555` a route key configured in RMQ can be `111/222/333/444/.555` or `111/222/333/444/.*` 
3. Not sure about what you mean by `public IUDX server`, but yes things are the same as told above. but there may be changes according to the client and IUDX platform security policies.

**Comment by pachori91** [comment]
Hi @kailash & @abhi4578  & Team,

Suppose on IUDX i registered my Ingestion adpator and obtained databroker access information.

SO my further queries are as below-

- if i push 2 records with same id, then what will consumer see, will consumer see two record or one last updated only?
- If i need to delete a record which i published already then what should be the steps i need to folow? Does it support deletetion of published record?


Thanks
Deepak Kumar

**Comment by kailash** [comment]
Hi @pachori91,


1. What consumers will see depends on the API used to fetch data, 
      - If the latest data API is used, only the latest record will be returned.
      - If another API (temporal, spatial, attribute or complex) is used, then all records satisfying the query parameters conditions will be returned
2. There is no delete API supported as of now, have a look at [api-docs](https://rs.iudx.org.in/apis) for more in-depth API knowledge.

**Comment by pachori91** [comment]
Hi @kailash 

Thanks for your reply,

So we can say that if we are insert 2 record with same Id, then IUDX will store both record with same id and Consumer will get 
data as per its query?

please correct me if my understanding is wrong here.

Thanks
Deepak Kumar

**Comment by kailash** [comment]
> Hi @kailash
> 
> Thanks for your reply,
> 
> So we can say that if we are insert 2 record with same Id, then IUDX will store both record with same id and Consumer will get data as per its query?
> 
> please correct me if my understanding is wrong here.
> 
> Thanks Deepak Kumar

Yes
