### ISSUE TITLE
Query Regrding Stream/Push Data to IUDX

### ISSUE THREAD

**Issue by pachori91** [datakaveri/iudx-resource-server#305]
Hi Team,

I have followed [Register Adaptor for Resouce](https://docs.iudx.org.in/docs/provider/provider_register_resource_server/) on my Local Instance to register adaptor.

Finally i got databroker enpoint with credential.

My Futher query is , do i need to write to same exchange which provided as "id" in Register Adpator API's response or no need to mention exchange while pushing data to RabbitMq? so that i can publish my data properly.

Is the route_key will be same as exchange id?
Does same thing apply for public IUDX Server?

Thanks
Deepak Kumar

**Comment by kailash** [comment]
Same as #301 and #302, please use those existing issues for related questions.
